---
# linux-nexus-win/installer/calamares/settings.conf
# Configuración principal de Calamares para Linux Nexus-Win

modules-search: [ local, /usr/lib/x86_64-linux-gnu/calamares/modules ]

instances:
- id:       nexus-postinstall
  module:   shellprocess
  config:   shellprocess-nexus.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - sources-yukk
  - machineid
  - fstab
  - restore-user
  - chrootcfg
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - users
  - displaymanager
  - grubcfg
  - bootloader
  - shellprocess@nexus-postinstall
  - umount
- show:
  - finished

branding: default
prompt-install: true
dont-chroot: false
binary-destination: /usr/bin/calamares
